### ISSUE TITLE
Android (ARM64) library long load time

### ISSUE THREAD

**Issue by ibaiGorordo** [3DTune-In/3dti_AudioToolkit_UnityWrapper#1]
Hi,

Thank you for the new release updates. The ARM64 Android version of the library for both versions of the v3.0 Release candidates take a long time (around 30 seconds) to load. I tested on a couple of Android devices (Oneplus 8, Oppo Find X3 Pro) but the results are the same.

However, the ARMv7 load quickly as expected, is there any issue with the ARM64 library, or is some setting required to work with ARM64?

Thank you,
Ibai

**Comment by timmb** [comment]
Hi Ibai

I'm only including builds for ARM64, not ARMv7. If you're linking to an ARMv7 build is it possible the library is simply not loading? Is the plugin actually functioning?

I've been testing the Android builds on a Samsung S8 although I don't have it to hand right now.

The biggest slow-down factor at load time seems to come from the calculation of Baer-Moore frequency smearing coefficients in the Hearing Loss simulator. Changing to use the Graf algorithm instead improves things.

If this doesn't help would you be able to send me a copy of a Unity project reproducing the slow down?

Thanks,
Tim

**Comment by areyesl** [comment]
Yes, if I may add something, the Baer-Moore algorithm requieres computing the inverse of a matrix the size of the audio frame which is quite costly especially if the audio frame size is large. So, another possibility is to reduce the frame size. In any case, the Graf algorithm is much lighter. 

Arcadio

**Comment by ibaiGorordo** [comment]
Hi, 

Thanks both for the quick reply. Changing to Graf worked perfectly (btw I am testing with the default example). Here are the Android log comparison for both methods, so you can compare how long is taking for every process.
[3DTI_AndroidTestLog_BaerMore.txt](https://github.com/3DTune-In/3dti_AudioToolkit_UnityWrapper/files/7524548/3DTI_AndroidTestLog_BaerMore.txt)
[3DTI_AndroidTestLog_Graf.txt](https://github.com/3DTune-In/3dti_AudioToolkit_UnityWrapper/files/7524549/3DTI_AndroidTestLog_Graf.txt)

In our application, we don't really need the hearing loss at the moment. But even though I disable the hearing loss simulator in the mixer, the calculations you mention are still happening. Is there any way to completely turn off the support for the Hearing loss simulation?

Thank you,
Ibai

**Comment by timmb** [comment]
You would need to remove the Hearing Loss simulation plugin from the mixer entirely. You should also remove the API_3DTI_HL component from the main camera when doing so as well.

**Comment by ibaiGorordo** [comment]
I see, thank you!
