### ISSUE TITLE
Using Custom HRTF in unity

### ISSUE THREAD

**Issue by fulviomissoni** [3DTune-In/3dti_AudioToolkit_UnityWrapper#3]
Hi,
I would need to use a custom HRTF in .sofa format within unity. If I add the data in the specific folder (Resources / HRTFs) this is not seen by the script (maybe because it is not in .binary format?) Can you suggest me a possible solution to use HRTFs in .sofa format or the procedure to get HRTF in .binary format?

**Comment by timmb** [comment]
Hi,

To add your own HRTF you just add the file into the folder alongside the bundled HRTFs and edit the filename to add `.bytes` to the end, so in your case the extension would become `.sofa.bytes`. Unity will only bundle binaries if they have that extension.

Note that the filename needs to include the sample rate, e.g. `44100` or `48000`.

I will be updating the docs shortly to make this clearer.

**Comment by timmb** [comment]
(I'll leave this issue open until the docs are updated)

**Comment by fulviomissoni** [comment]
Thank you very much!
