### ISSUE TITLE
Standalone Meta VR headset support

### ISSUE THREAD

**Issue by RaunDiscovery** [3DTune-In/3dti_AudioToolkit_UnityWrapper#4]
Hi! 

I would like to use the wrapper in a standalone VR application for the Meta Quest 3 (i.e. no PC) but so far I haven't been able to get spatialization up and running. 

- Audio is coming through fine when I run the Unity output *.apk file in the headset, but there's no head-tracked spatialization.
- Spatialization is working fine in the Meta's Unity XR Simulator.

Anyone else got it working? Any tips?

Thanks!

**Comment by timmb** [comment]
Hi

No Quest 3 to test with, but I had a lot of difficulty getting the toolkit to play nice with the more recent Meta SDK on the Quest 2.

I was successful in the end. I think there is some fighting between the native libraries of the toolkit and the SDK. I searched extensively but couldn't pin down where.

Can you try building and running the bundled sample scene on your headset? Just open the BuildUnityWrapperPackage of this repo in Unity 2019.4.40f1, without adding the Meta SDK, etc. It should run in a window (on the headset) and you should be able to hear the voice panning around your head.

For me, I think I then did these steps and it was still working:
- Add Meta Core SDK only
- Add Oculus XR package
- Run Oculus setup tools and do everything it asks
- Double check toolkit is still set as the project spatializer
- Replace the Main Camera with the Meta camera rig

I advise using source control and testing frequently along the way. If it does stop working, then before reverting, try closing Unity, deleting the library, reopening then rebuilding. I must have updated Unity version at some point too.

Please document your steps and let us know.

Tim

**Comment by RaunDiscovery** [comment]
Hi Tim,

To give a brief update, I managed to solve my issue by combining the use of Oculus' own Spatializer plugin with the 3DTune-In HA + HL simulators. This satisfies my needs for now, but I will give your method a try if I get a moment.

Best,
Rasmus

**Comment by fulviomissoni** [comment]
Hi @RaunDiscovery,

I am working with 3DTI on Meta Quest 3 with the Meta SDK. Following both: the steps in the README and the ones suggested by Tim everything works fine, without any tracking problems. 

Hopefully, this should be useful for your problem.

Fulvio

**Comment by timmb** [comment]
Closing for now as issue seems to be resolved.
